version: 0.1

phases:
  install:
    commands:
      - echo Starting postgresql...
      - service postgresql restart
      - bundle install --with test
  pre_build:
    commands:
      - echo Preparing database to run tests...
      - RAILS_ENV=test bundle exec rake db:setup db:migrate
  build:
    commands:
      - echo Running rspec tests...
      - bundle exec rspec spec/
