source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>=2.5.0'

# my own gem to override default laydate loading css in js issue
gem 'laydate-rails', '~> 0.2.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.1'
# Use pg the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma', '~> 3.12'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
#
gem 'activeadmin'
gem 'devise'
gem 'thin'
gem 'cancancan'
# history/auditing
gem 'paper_trail'
# for tracking associations
# gem 'paper_trail-association_tracking'
# directly upload media to s3
gem 'aws-sdk-s3', '~> 1'
# Use Unicorn as the app server
gem 'unicorn'

# mqtt client for pub/sub topic
gem 'mqtt'

# multiple level parent management
gem 'ancestry'

# for semantic version comparison
gem 'semantic'

# paginate
gem 'kaminari'
# Paginate in your headers
gem 'api-pagination'

# used to decode and encode JWT auth tokens for API
gem 'warden-jwt_auth'
# used for token revocation in API
gem 'devise-jwt'

# allow any origin
gem 'rack-cors'

# production error sent to sentry.io
group :production do
  gem 'sentry-raven'
end

# Serialisation for non-jsonapi format
gem 'active_model_serializers'
# Serialisation for jsonapi format
gem 'fast_jsonapi'

# Manage position attr in model
gem 'acts_as_list'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Use sidekiq for async jobs
gem 'sidekiq'
gem 'sidekiq-failures'

# User foreman to run multiple processes
gem 'foreman'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry'
  # .env variables
  gem 'dotenv-rails'
  # Use annotate gem to annotate model.rb files with attributes
  gem 'annotate', github: 'ctran/annotate_models'
  # Using better errors to help development
  gem 'better_errors'
  # Using Binding of Caller gem to enable variable inspection in better errors gem
  gem 'binding_of_caller'
  # Ruby syntax guard
  gem 'rubocop'
  # Use rspec for BDD (behaviour-driven development)
  gem 'rspec-rails'
  gem 'factory_bot_rails'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
  # Coverage reports for your tests
  gem 'simplecov', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
